# Generated by Django 3.2.2 on 2021-05-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Major', models.CharField(max_length=20)),
                ('In_Dormitory', models.BooleanField()),
                ('MBTI', models.CharField(max_length=10)),
                ('Hobby', models.CharField(max_length=100)),
                ('Nickname', models.CharField(max_length=100)),
                ('Favorite_Food', models.TextField()),
            ],
        ),

        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Major', models.CharField(max_length=20)),
                ('In_Dormitory', models.BooleanField()),
                ('MBTI', models.CharField(max_length=10)),
                ('Hobby', models.CharField(max_length=100)),
                ('Nickname', models.CharField(max_length=100)),
                ('Favorite_Food', models.TextField()),
            ],
        )
    ]
